name: Deploy serverless app - DEVELOPMENT
on:
  push:
    branches:
      - development
jobs:
  deploy:
    name: Deploy Project - DEVELOPMENT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Install typescript
        run: |
          npm install -g typescript
      - name: Compile typescript
        run: |
          npm run build
      - name: Deploy app to development stage via serverless framework
        uses: serverless/github-action@v3.2
        with:
          args: deploy --stage development
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}